from skimage import io, color, filters
img=io.imread('baboon.png')
dimens=color.guess_spatial_dimensions(img)
print(dimens,type(dimens))
print(img.shape)
img_gs=color.rgb2gray(img)
io.imsave('baboon-gs.png',img_gs)
dimens=color.guess_spatial_dimensions(img_gs)
print(dimens,type(dimens))
show_grayscale=io.imshow(img_gs)
# io.show()
edges=filters.sobel(img_gs)
io.imshow(edges)
io.show()